In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from IPython.display import HTML

In [3]:
data = pd.read_csv("employee_data.csv")
data.head()

html_table = data.to_html(index=False, justify='center')

display(HTML(html_table))

In [4]:
data["Join_Date"] = pd.to_datetime(data["Join_Date"])

In [8]:
data["Name"] = data["Name"].astype(str)

In [9]:
scaler = StandardScaler()
data["Salary_Scaled"] = scaler.fit_transform(data[["Salary"]])

In [11]:
data.head()
html_table = data.to_html(index=False, justify='center')

display(HTML(html_table))

In [12]:
data.to_csv("standardized_employee_data.csv", index=False)

In [14]:
data.head()
html_table = data.to_html(index=False, justify='center')

display(HTML(html_table))